name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
          include: 'jdk'

      - name: Build with Maven
        run: mvn clean package

      - name: Create Windows EXE
        shell: cmd
        run: |
          jpackage --name alwaysthere-1.0-SNAPSHOT ^
            --input target/ ^
            --main-jar alwaysthere-1.0-SNAPSHOT.jar ^
            --main-class io.github.artemget.alwaysthere.Entrypoint ^
            --type exe ^
            --win-console ^
            --dest target

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/*.exe
            target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
