name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Create EXE with Launch4j
        run: |
          choco install launch4j -y
          launch4j config.xml

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/alwaysthere-1.0-SNAPSHOT.exe
            target/alwaysthere-1.0-SNAPSHOT.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
