name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Install Launch4j
        shell: cmd
        run: choco install launch4j

      - name: Run Launch4j
        run: C:\Program Files (x86)\Launch4j\launch4j.exe config.xml
        working-directory: ${{ github.workspace }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/*.exe
            target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
