name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Download and setup Launch4j
        run: |
          $url = "https://downloads.sourceforge.net/project/launch4j/launch4j-3/3.14/launch4j-3.14-win32.zip"
          Invoke-WebRequest -Uri $url -OutFile launch4j.zip
          Expand-Archive -Path launch4j.zip -DestinationPath .
          $env:PATH += ";$pwd\launch4j"
          launch4j config.xml

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/alwaysthere-1.0-SNAPSHOT.exe
            target/alwaysthere-1.0-SNAPSHOT.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
